In [2]:
# Import neccessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load processed data
crop_df = pd.read_csv('../data/processed/Processed_Crop_Yield.csv')
rainfall_df = pd.read_csv('../data/processed/Processed_Rainfall_Data.csv')

In [3]:
#  Extract Year from Rainfall Date
rainfall_df['year'] = pd.to_datetime(rainfall_df['date']).dt.year

In [4]:
# Aggregate Rainfall by State and Year
rainfall_features = rainfall_df.groupby(['state_name', 'year']).agg({
    'actual_rainfall': ['mean', 'sum', 'std'],
    'deviation': 'mean'
}).reset_index()

# Flatten multi-level column names
rainfall_features.columns = ['state_name', 'year', 'avg_rainfall', 'total_rainfall', 'std_rainfall', 'mean_deviation']

# Preview rainfall features
rainfall_features.loc[1:10]

# Preview crop features
crop_df.loc[1:10]

# Preview 'crop' column
# crop_df['Crop']

    Year                                               Crop  Yield_kg_per_ha
1   1962  Anise, badian, coriander, cumin, caraway, fenn...            500.0
2   1963  Anise, badian, coriander, cumin, caraway, fenn...            500.0
3   1964  Anise, badian, coriander, cumin, caraway, fenn...            500.0
4   1965  Anise, badian, coriander, cumin, caraway, fenn...            500.0
5   1966  Anise, badian, coriander, cumin, caraway, fenn...            494.8
6   1967  Anise, badian, coriander, cumin, caraway, fenn...            494.8
7   1968  Anise, badian, coriander, cumin, caraway, fenn...            494.8
8   1969  Anise, badian, coriander, cumin, caraway, fenn...            452.6
9   1970  Anise, badian, coriander, cumin, caraway, fenn...            452.6
10  1971  Anise, badian, coriander, cumin, caraway, fenn...            452.6

In [5]:
# Add 'year' column if not already present
rainfall_df['year'] = pd.to_datetime(rainfall_df['date']).dt.year

rainfall_df.loc[0:10]
# crop_df

,date,state_code,state_name,actual_rainfall,normal_rainfall,deviation,year
0,2009-01-20,5,Uttarakhand,0.00,2.61,-100.00,2009
1,2009-01-20,18,Assam,0.00,0.62,-100.00,2009
2,2009-01-20,36,Telangana,0.00,0.17,-100.00,2009
3,2009-01-20,2,Himachal Pradesh,0.53,4.46,-88.12,2009
4,2009-01-20,1,Jammu And Kashmir,0.00,3.55,-100.00,2009
5,2009-01-20,17,Meghalaya,0.00,0.21,-100.00,2009
6,2009-01-20,27,Maharashtra,0.00,0.15,-100.00,2009
7,2009-01-20,3,Punjab,0.00,1.19,-100.00,2009
8,2009-01-20,20,Jharkhand,0.00,0.69,-100.00,2009
9,2009-01-20,28,Andhra Pradesh,0.00,0.07,-100.00,2009
10,2009-01-20,12,Arunachal Pradesh,0.00,0.69,-100.00,2009

In [6]:
# National aggregation by year
rainfall_yearly = rainfall_df.groupby('year').agg({
    'actual_rainfall': ['mean', 'std', 'sum'],
    'deviation': 'mean'
}).reset_index()

In [7]:
# Flatten column names
rainfall_yearly.columns = [
    'year',
    'rainfall_mean',
    'rainfall_std',
    'rainfall_total',
    'rainfall_deviation'
]

In [14]:
# Save to processed folder
rainfall_yearly.to_csv('../data/processed/Aggregated_Rainfall_Data.csv', index=False)

# crop_df
rainfall_yearly

    year  rainfall_mean  rainfall_std  rainfall_total  rainfall_deviation
0   2009       3.977650      9.869378        43495.60            3.167084
1   2010       4.824177     10.094051        55535.93           51.041491
2   2011       4.105025      8.813380        47257.05           15.314798
3   2012       3.762025      8.157801        43308.43            3.660175
4   2013       4.441565      9.582673        51131.30           39.384337
5   2014       4.032844      9.888359        46426.10           20.912806
6   2015       4.212624      9.924950        48495.73           50.438758
7   2016       4.103886      9.115404        47243.94            0.242713
8   2017       4.472614     10.191875        51488.73           17.217206
9   2018       3.989807      9.067655        45930.66           24.063577
10  2019       4.676201     11.032972        53832.43           52.727130
11  2020       4.673186     10.597684        51035.86           56.783572
12  2021       4.503422      9.752264        50222.16          122.470193
13  2022       4.841742     11.416030        54823.04           30.394487
14  2023       4.196804     10.050079        48045.01           99.499005
15  2024       0.816166      4.121047         1941.66           26.134746

In [31]:
crop_df

      year                                               Crop  Yield_kg_per_ha
0     1961  Anise, badian, coriander, cumin, caraway, fenn...            500.0
1     1962  Anise, badian, coriander, cumin, caraway, fenn...            500.0
2     1963  Anise, badian, coriander, cumin, caraway, fenn...            500.0
3     1964  Anise, badian, coriander, cumin, caraway, fenn...            500.0
4     1965  Anise, badian, coriander, cumin, caraway, fenn...            500.0
...    ...                                                ...              ...
4934  2019  Wheat                                         ...           3533.4
4935  2020  Wheat                                         ...           3439.8
4936  2021  Wheat                                         ...           3520.8
4937  2022  Wheat                                         ...           3537.3
4938  2023  Wheat                                         ...           3520.7

[4939 rows x 3 columns]

In [ ]:
# Load processed crop yield data
crop_df = pd.read_csv('../data/processed/Processed_Crop_Yield.csv')

# Rename for consistency
crop_df.rename(columns={'Year': 'year'}, inplace=True)

# Keep only the relevant columns
crop_df = crop_df[['year', 'Crop', 'Yield_kg_per_ha']]  # Include crop and yield columns

# Rename columns for clarity
crop_df.rename(columns={'Item': 'crop', 'Value': 'yield'}, inplace=True)

# Merge with aggregated rainfall data
merged_df = pd.merge(crop_df, rainfall_yearly, on='year', how='inner')

# Save the final model dataset
merged_df.to_csv('../data/processed/Final_Model_Data.csv', index=False)

print("✅ Final merged dataset: Final_Model_Data.csv saved! with crop and yield included!")

✅ Final merged dataset: Final_Model_Data.csv saved! with crop and yield included!

In [33]:
merged_df

,year,Crop,Yield_kg_per_ha,rainfall_mean,rainfall_std,rainfall_total,rainfall_deviation
0,2009,"Anise, badian, coriander, cumin, caraway, fenn...",684.4,3.977650,9.869378,43495.60,3.167084
1,2010,"Anise, badian, coriander, cumin, caraway, fenn...",736.7,4.824177,10.094051,55535.93,51.041491
2,2011,"Anise, badian, coriander, cumin, caraway, fenn...",774.7,4.105025,8.813380,47257.05,15.314798
3,2012,"Anise, badian, coriander, cumin, caraway, fenn...",774.6,3.762025,8.157801,43308.43,3.660175
4,2013,"Anise, badian, coriander, cumin, caraway, fenn...",784.0,4.441565,9.582673,51131.30,39.384337
...,...,...,...,...,...,...,...
1168,2019,Wheat ...,3533.4,4.676201,11.032972,53832.43,52.727130
1169,2020,Wheat ...,3439.8,4.673186,10.597684,51035.86,56.783572
1170,2021,Wheat ...,3520.8,4.503422,9.752264,50222.16,122.470193
1171,2022,Wheat ...,3537.3,4.841742,11.416030,54823.04,30.394487
1172,2023,Wheat ...,3520.7,4.196804,10.050079,48045.01,99.499005