In [2]:
# Import neccessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load processed data
crop_df = pd.read_csv('../data/processed/Processed_Crop_Yield.csv')
rainfall_df = pd.read_csv('../data/processed/Processed_Rainfall_Data.csv')

In [3]:
#  Extract Year from Rainfall Date
rainfall_df['year'] = pd.to_datetime(rainfall_df['date']).dt.year

In [4]:
# Aggregate Rainfall by State and Year
rainfall_features = rainfall_df.groupby(['state_name', 'year']).agg({
    'actual_rainfall': ['mean', 'sum', 'std'],
    'deviation': 'mean'
}).reset_index()

# Flatten multi-level column names
rainfall_features.columns = ['state_name', 'year', 'avg_rainfall', 'total_rainfall', 'std_rainfall', 'mean_deviation']

# Preview rainfall features
rainfall_features.loc[1:10]

# Preview crop features
crop_df.loc[1:10]

# Preview 'crop' column
# crop_df['Crop']

    Year                                               Crop  Yield_kg_per_ha
1   1962  Anise, badian, coriander, cumin, caraway, fenn...            500.0
2   1963  Anise, badian, coriander, cumin, caraway, fenn...            500.0
3   1964  Anise, badian, coriander, cumin, caraway, fenn...            500.0
4   1965  Anise, badian, coriander, cumin, caraway, fenn...            500.0
5   1966  Anise, badian, coriander, cumin, caraway, fenn...            494.8
6   1967  Anise, badian, coriander, cumin, caraway, fenn...            494.8
7   1968  Anise, badian, coriander, cumin, caraway, fenn...            494.8
8   1969  Anise, badian, coriander, cumin, caraway, fenn...            452.6
9   1970  Anise, badian, coriander, cumin, caraway, fenn...            452.6
10  1971  Anise, badian, coriander, cumin, caraway, fenn...            452.6

In [5]:
# Add 'year' column if not already present
rainfall_df['year'] = pd.to_datetime(rainfall_df['date']).dt.year

rainfall_df.loc[0:10]
# crop_df

,date,state_code,state_name,actual_rainfall,normal_rainfall,deviation,year
0,2009-01-20,5,Uttarakhand,0.00,2.61,-100.00,2009
1,2009-01-20,18,Assam,0.00,0.62,-100.00,2009
2,2009-01-20,36,Telangana,0.00,0.17,-100.00,2009
3,2009-01-20,2,Himachal Pradesh,0.53,4.46,-88.12,2009
4,2009-01-20,1,Jammu And Kashmir,0.00,3.55,-100.00,2009
5,2009-01-20,17,Meghalaya,0.00,0.21,-100.00,2009
6,2009-01-20,27,Maharashtra,0.00,0.15,-100.00,2009
7,2009-01-20,3,Punjab,0.00,1.19,-100.00,2009
8,2009-01-20,20,Jharkhand,0.00,0.69,-100.00,2009
9,2009-01-20,28,Andhra Pradesh,0.00,0.07,-100.00,2009
10,2009-01-20,12,Arunachal Pradesh,0.00,0.69,-100.00,2009